apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/skipperkongen/poplesia.git
    targetRevision: HEAD
    path: argo/poplesia
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: poplesia
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
